### ISSUE TITLE
Pool buffer allocation error

### ISSUE THREAD

**Issue by bogdanPricope** [OpenDataPlane/odp-dpdk#194]
odp_dpdk, v1.36, 'linux-generic' platform, default odp configuration
Test conditions:
 - thread 1: create a buffer pool (32 items) and allocate a buffer
 - thread 2: allocate a second buffer

What I am seeing is that the second buffer cannot be allocated unless I have at least 64 items in the pool.
I guess this is related to all those 'cache size', 'burst size' settings but can you explain this behavior?

odp_pool_param_init(&pool_params);
pool_params.buf.size  = 40;
pool_params.buf.align = 0;
pool_params.buf.num   = 32;
pool_params.type      = ODP_POOL_BUFFER;

test_pool = odp_pool_create("test_test", &pool_params);

Pool info
---------
  pool            15
  name            test_test
  pool type       buffer
  pool shm        52
  user area shm   0
  num             32
  align           64
  headroom        0
  seg len         40
  max data len    0
  tailroom        0
  block size      128
  uarea size      0
  shm size        4096
  base addr       0x7f2a8712b000
  max addr        0x7f2a8712bfff
  uarea shm size  0
  uarea base addr (nil)
  cache size      256
  burst size      32

**Comment by MatiasElo** [comment]
Hi Bogdan,

What you are seeing is indeed most likely caused by pool local caching. You can use `odp_pool_param_t.buf.cache_size` parameter to adjust the maximum number of buffers each thread is allowed to cache.

The `local_cache_size` config file option can be used to change the default value for this parameter (set by `odp_pool_param_init()`). `burst_size` option is used inside the pool implementation to reduce the number of global pool accesses. E.g. if an application tries to allocate a single buffer, `burst_size` buffers are allocated from global pool and the extra buffers are stored in thread local cache.

**Comment by bogdanPricope** [comment]
Hi Matias,

I see... it caches per thread up to 'local_cache_size' (256) buffers in 'burst_size' (32) groups. I guess this is why for my 2 threads setup it worked with 33 but it didn't worked with 32. Unfortunately, 'burst size' cannot be set or read at application level...

For my case, it worked with buf.cache_size = 0 (disable).
Kind of weird tho..

**Comment by MatiasElo** [comment]
Hi,

The `burst_size` config option is used for pool implementation performance tuning and normally an application doesn't have to care about it. If used local pool cache size is less than `burst_size`, the `burst_size` value is automatically scaled down.

To prevent cache starvation, you have to make sure your pool is large enough:`odp_pool_param_t.buf.num` >= `num_threads` *  `odp_pool_param_t.buf.cache_size`.

**Comment by bogdanPricope** [comment]
Hi Matias,

Thank you for the details.

For my case a larger pool is not an option as I am targeting to reduce the memory footprint. But disabling local cache for some cases (reduced number of items) worked fine.

Best regards
